language: node_js

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: yarn

script:
  - yarn
  - yarn lint
  - yarn build:webpack
